language: java
jdk:
- openjdk7
notifications:
  email:
  - haroon_sheikh@hotmail.co.uk
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
